name: Update Redirects

on:
  schedule:
    - cron: "0 5 * * *"  # 每天 5:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-redirects:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 运行脚本
        run: python url.py

      - name: 提交更改
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add redirects.json log.txt
          git commit -m "更新 redirects.json 和 log.txt" || echo "No changes to commit"
          git push
